class CivicLocale {
  static Map<String, dynamic> dictionary = <String, dynamic>{
    "EN": {
      "general": {
        "close-button-label": "Close",
        "cancel-button-label": "Cancel"
      },
      "dialogs": {
        "show-message-primary-button-label": "Close",
        "link-account-title": "Link your member account",
        "link-account-input-label": "Member account",
        "link-account-input-hint": "Account",
        "link-account-password-input-label": "Member password",
        "link-account-password-input-hint": "Password",
        "link-account-cancel-button-label": "Cancel",
        "link-account-error-hint": "Please fill all fields",
        "unlink-account-title": "Warning!",
        "unlink-account-subtitle": "Do you want to unlink your member account from this center?",
        "unlink-account-cancel-button-label": "Cancel",
        "unlink-account-fail-message": "Failed to link",
        "unlink-account-primary-button": "Unlink",
        "link-account-unavailable-title": "Unavailable",
        "link-account-unavailable-subtitle": "Please login to your account to use this feature.",
        "link-account-unavailable-primary-button-label": "Close",
        "center-booking-member-required-title": "Unavailable",
        "center-booking-member-required-subtitle": "Please link your member account to use this feature",
        "center-booking-member-required-button-label": "Close",
        "center-topup-unavailable-title": "Unavailable",
        "center-topup-unavailable-subtitle": "Please login to your account to use this feature",
        "center-topup-unavailable-primary-button": "Close",
        "center-booking-disabled-title": "Disabled",
        "center-booking-disabled-subtitle": "Center does not allow booking",
        "center-booking-disabled-primary-button": "Close",
        "center-disabled-title": "Disabled",
        "center-disabled-subtitle": "Center does not allow online topups",
        "center-disabled-subtitle-primary-button": "Close",
        "center-topup-payment-method-label": "Please choose payment processor",
        "center-topup-no-card-title": "No available bank cards for this country",
        "center-topup-no-card-subtitle": "You don't have any bank cards for this payment processor added, would you like to add one?",
        "center-topup-no-card-secondary-button-label": "Close",
        "center-topup-no-card-primary-button-label": "Add",
        "center-topup-no-card-modal-title": "Bank card is not linked",
        "center-topup-no-card-modal-subtitle": "Your bank card is not linked to this center. Link your card to perform online topups",
        "center-topup-no-card-modal-secondary-button-label": "Close",
        "center-topup-no-card-modal-primary-button-label": "Link",
        "center-topup-cards-load-failed": "Failed to fetch",
        "center-topup-member-account-label": "Member account",
        "center-topup-member-account-input-hint": "Account",
        "center-topup-bank-card-label": "Bank card",
        "center-topup-bank-card-input-hint": "Bank card",
        "center-topup-amount-label": "Topup amount",
        "center-topup-successful-title": "Transaction is successful",
        "center-topup-successful-subtitle": "Your transaction went successfully! You can see your transactions history on profile page.",
        "center-topup-3d-security-fail-title": "Could not process 3D security link",
        "center-topup-3d-security-fail-subtitle": "We could not process 3D security link sent by payment provider",
        "center-topup-fail-title": "Failed to process topup",
        "center-topup-empty-inputs-title": "Data is required",
        "center-topup-empty-inputs-subtitle": "Please fill all required fields",
        "bank-cards-route-card-create-error-title": "Could not create bank card",
        "bank-cards-empty-inputs-title": "Data is required",
        "bank-cards-empty-inputs-subtitle": "Please enter code you received",
        "bank-cards-verify-card-fail-title": "Could not verify card",
        "bank-cards-verification-code-send-fail": "Failed to send code",
        "bank-cards-failed-to-link": "Failed to link the card",
        "booking-success-title": "Success!",
        "booking-success-caption": "Your booking successfully placed",
        "booking-failed-to-book": "Failed to place booking",
        "booking-empty-inputs-title": "Data is required",
        "booking-empty-inputs-subtitle": "Please fill all required fields",
        "settings-success-title": "Success!",
        "settings-fail-title": "Fail",
        "settings-account-change-success-caption": "Account name changed successfully",
        "settings-account-change-fail-caption": "Could not change account name",
        "settings-language-change-success-caption": "Interface language changed successfully",
        "settings-language-change-fail-caption": "Could not change interface language, please check your internet connection",
        "settings-theme-change-success-caption": "Interface theme changed successfully",
        "settings-theme-change-fail-caption": "Could not change interface theme, please check your internet connection",
        "settings-password-change-success-caption": "Password changed successfully",
        "settings-password-change-fail-caption": "Could not change password"
      },
      "home-route": {
        "bottom-navbar-home-label": "Home",
        "bottom-navbar-search-label": "Search",
        "bottom-navbar-profile-label": "Profile",
        "home-greeting-subtitle": "Welcome to iCafePlay",
        "home-greeting-title": "Where we are going today?",
        "home-search-button-label": "Search",
        "home-top-centers-title": "Top centers",
        "home-top-centers-subtitle": "Discover our top centers",
        "home-center-of-the-day-title": "Center of the day",
        "home-center-of-the-day-subtitle": "This center is today's spotlight",
        "home-exception-hint": "Could not load centers list",
        "search-input-hint": "Search",
        "profile-settings-bookings-label": "Bookings history",
        "profile-settings-bank-cards-label": "My bank cards",
        "profile-settings-transactions-label": "Transactions history",
        "profile-settings-accounts-label": "Member accounts",
        "profile-settings-settings-label": "Settings",
        "profile-settings-support-label": "Support",
        "profile-settings-logout-label": "Logout",
        "profile-modals-bookings-empty-title": "No bookings were found",
        "profile-modals-bookings-empty-hint": "You don't have any active bookings. Start booking PCs and they will appear here",
        "profile-modals-bookings-title": "My bookings",
        "profile-modals-bookings-booking-date": "Date",
        "profile-modals-bookings-booking-time": "Time",
        "profile-modals-bookings-booking-pc": "PC",
        "profile-modals-bookings-booking-minutes": "Minutes",
        "profile-modals-bank-cards-empty-title": "No bank cards were found",
        "profile-modals-bank-cards-empty-hint": "You don't have any bank cards. You can link your bank card in any center's page",
        "profile-modals-bank-cards-title": "My bank cards",
        "profile-modals-bank-cards-warning-title": "Warning!",
        "profile-modals-bank-cards-warning-details": "Deleting will cause removing all data related with bank cards, including transactions history!",
        "profile-modals-bank-cards-remove-button-label": "Remove",
        "profile-modals-transactions-dialog-title": "Select bank card",
        "profile-modals-transactions-empty-title": "No transactions were found",
        "profile-modals-transactions-empty-hint": "You don't have any transactions. Your topups history will be visible here",
        "profile-modals-transactions-title": "Transactions history",
        "profile-modals-transactions-transaction-center": "Center:",
        "profile-modals-transactions-transaction-amount": "Amount:",
        "profile-modals-transactions-transaction-date": "Date:",
        "profile-modals-transactions-transaction-account": "Account:",
        "profile-modals-transactions-transaction-status": "Status:",
        "profile-modals-transactions-exception-hint": "Failed to load transactions list:",
        "profile-modals-accounts-empty-title": "No member accounts were found",
        "profile-modals-accounts-empty-hint": "You don't have any accounts. Start linking your local member accounts and they will appear here",
        "profile-modals-accounts-title": "My member accounts",
        "profile-modals-support-exception-hint": "Could not open telegram",
        "profile-modals-support-exception-comment": "Failed to process telegram link (",
        "profile-modals-logout-confirm-title": "Are you sure?",
        "profile-modals-logout-confirm-hint": "Do you really want to logout?",
        "profile-modals-logout-confirm-button-label": "Logout",
        "profile-exception-hint": "Something went wrong",
      },
      "settings-route": {
        "change-name-section-title": "Settings",
        "change-name-section-label": "Change account name",
        "change-name-section-input-hint": "Name",
        "change-name-section-button-label": "Change",
        "language-section-title": "Customization",
        "language-section-label": "Change interface language",
        "dark-theme-section-label": "Change interface theme",
        "theme-option-dark-label": "Dark",
        "theme-option-bright-label": "Bright",
        "password-reset-section-title": "Reset password",
        "password-reset-section-old-label": "Old password",
        "password-reset-section-old-input-hint": "Old password",
        "password-reset-section-new-label": "New password",
        "password-reset-section-new-input-hint": "New password",
        "password-reset-section-button-label": "Change"
      },
      "center-route": {
        "link-account-button-label": "Link account",
        "link-account-button-label-alt": "Account",
        "center-account-title": "Member account",
        "center-account-subtitle": "Balance",
        "center-account-cash-balance-label": "Cash balance",
        "center-account-points-balance-label": "Points balance",
        "center-account-coins-balance-label": "Coins balance",
        "center-account-bonus-balance-label": "Bonus balance",
        "center-details-title": "Details",
        "center-details-offers-label": "Offers",
        "center-details-zones-label": "Zones",
        "center-details-address-label": "Address",
        "center-call-failed-title": "Failed",
        "center-call-failed-subtitle": "Could not open phone number",
        "center-call-button-label": "Call",
        "center-location-title": "Location is unavailable",
        "center-location-subtitle": "Center's location is unavailable",
        "center-location-button-label": "Location",
        "center-subcenters-title": "Subcenters",
        "center-footer-button-topup-button-label": "Topup",
        "center-footer-button-booking-button-label": "Booking",
        "failed-to-load-data": "Could not load center (and related) data"
      },
      "bank-cards-route": {
        "bank-cards-route-title": "New bank card",
        "bank-cards-route-subtitle": "Choose payment processor",
        "bank-cards-card-details-label": "Card details",
        "bank-cards-card-details-input-hint": "Card number",
        "bank-cards-card-expiry-input-hint": "mm/yy",
        "bank-cards-name-on-card-input-hint": "Name on the card",
        "bank-cards-phone-input-hint": "Phone number",
        "bank-cards-first-step-button-label": "Create",
        "verification-code-sent-text": "Verification code has been sent",
        "verification-code-timeout-label": "Code",
        "verification-code-input-label": "Enter one time code you received",
        "bank-cards-second-step-button-label": "Verify",
        "verification-code-resend-button-label": "Resend code",
        "verification-code-resent-text": "Requested new verification code",
        "link-bank-card-title": "Bank card is not linked",
        "link-bank-card-subtitle": "Your bank card is not linked to this center. Link your card to perform online topups",
        "link-bank-card-button-label": "Link card",
        "link-bank-card-failed-to-fetch": "Could not load user data",
      },
      "booking-route": {
        "booking-route-title": "Book a PC",
        "member-input-hint": "Member",
        "center-input-hint": "Center",
        "date-input-hint": "Date",
        "time-input-hint": "Time",
        "minutes-input-hint": "Minutes",
        "booking-primary-button-label": "Book",
        "booking-failed-to-fetch-list": "Could not load computers and bookings list"
      },
      "authorization-route": {
        "email-input-hint": "Email",
        "password-input-hint": "Password",
        "forgot-password-button-label": "Forgot password?",
        "login-button-label": "Login",
        "register-button-label": "Register",
      },
      "registration-route": {
        "registration-route-title": "Registration",
        "name-input-hint": "Name",
        "country-input-hint": "Choose country",
        "choose-country-search-hint": "Search",
        "email-input-hint": "Email",
        "password-input-hint": "Password",
        "empty-input-title": "Please fill all required fields!",
        "login-button-label": "Sign up",
        "failed-to-fetch": "Could not load countries list.",
      }
    },
    "RU": {
      "general": {
        "close-button-label": "Закрыть",
        "cancel-button-label": "Отмена"
      },
      "dialogs": {
        "show-message-primary-button-label": "Закрыть",
        "link-account-title": "Свяжите свою учетную запись",
        "link-account-input-label": "Учетная запись",
        "link-account-input-hint": "Аккаунт",
        "link-account-password-input-label": "Пароль участника",
        "link-account-password-input-hint": "Пароль",
        "link-account-cancel-button-label": "Отмена",
        "link-account-error-hint": "Пожалуйста, заполните все поля",
        "unlink-account-title": "Внимание!",
        "unlink-account-subtitle": "Вы действительно хотите отменить привязку своей учетной записи к этому центру?",
        "unlink-account-cancel-button-label": "Отмена",
        "unlink-account-fail-message": "Не удалось привязать аккаунт",
        "unlink-account-primary-button": "Отвязать",
        "link-account-unavailable-title": "Недоступно",
        "link-account-unavailable-subtitle": "Пожалуйста, войдите в свою учетную запись, чтобы использовать эту функцию.",
        "link-account-unavailable-primary-button-label": "Закрыть",
         "center-booking-member-required-title": "Недоступно",
        "center-booking-member-required-subtitle": "Пожалуйста, привяжите свой аккаунт центра, чтобы использовать эту функцию.",
        "center-booking-member-required-button-label": "Закрыть",
        "center-topup-unavailable-title": "Недоступно",
        "center-topup-unavailable-subtitle": "Пожалуйста, войдите в свою учетную запись, чтобы использовать эту функцию",
        "center-topup-unavailable-primary-button": "Закрыть",
        "center-booking-disabled-title": "Отключено",
        "center-booking-disabled-subtitle": "Центр не допускает онлайн бронирование",
        "center-booking-disabled-primary-button": "Закрыть",
        "center-disabled-title": "Отключено",
        "center-disabled-subtitle": "Центр не допускает онлайн-пополнений",
        "center-disabled-subtitle-primary-button": "Закрыть",
        "center-topup-payment-method-label": "Пожалуйста, выберите платежную систему",
        "center-topup-no-card-title": "Нет доступных банковских карт для этой страны",
        "center-topup-no-card-subtitle": "У вас нет банковских карт для этого платежного процессора, хотите ли вы добавить одну?",
        "center-topup-no-card-secondary-button-label": "Закрыть",
        "center-topup-no-card-primary-button-label": "Добавить",
        "center-topup-no-card-modal-title": "Банковская карта не привязана",
        "center-topup-no-card-modal-subtitle": "Ваша банковская карта не привязана к этому центру. Привяжите свою карту для выполнения онлайн-пополнений",
        "center-topup-no-card-modal-secondary-button-label": "Закрыть",
        "center-topup-no-card-modal-primary-button-label": "Привязать",
        "center-topup-cards-load-failed": "Не удалось загрузить",
        "center-topup-member-account-label": "Логин",
        "center-topup-member-account-input-hint": "Логин",
        "center-topup-bank-card-label": "Банковская карта",
        "center-topup-bank-card-input-hint": "Банковская карта",
        "center-topup-amount-label": "Сумма пополнения",
        "center-topup-successful-title": "Транзакция прошла успешно",
        "center-topup-successful-subtitle": "Ваша транзакция прошла успешно! Вы можете увидеть историю ваших транзакций на странице профиля.",
        "center-topup-3d-security-fail-title": "Не удалось обработать ссылку 3D-безопасности",
        "center-topup-3d-security-fail-subtitle": "Мы не смогли обработать ссылку 3D-безопасности, отправленную поставщиком платежных услуг",
        "center-topup-fail-title": "Не удалось обработать пополнение",
        "center-topup-empty-inputs-title": "Заполните все поля",
        "center-topup-empty-inputs-subtitle": "Пожалуйста, заполните все обязательные поля!",
        "bank-cards-route-card-create-error-title": "Не удалось создать банковскую карту",
        "bank-cards-empty-inputs-title": "Заполните все поля",
        "bank-cards-empty-inputs-subtitle": "Введите полученный вами код.",
        "bank-cards-verify-card-fail-title": "Не удалось подтвердить карту",
        "bank-cards-verification-code-send-fail": "Не удалось отправить код",
        "bank-cards-failed-to-link": "Не удалось привязать карту",
        "booking-success-title": "Успешно!",
        "booking-success-caption": "Ваше бронирование успешно оформлено",
        "booking-failed-to-book": "Не удалось оформить бронирование",
        "booking-empty-inputs-title": "Заполните все поля",
        "booking-empty-inputs-subtitle": "Пожалуйста, заполните все обязательные поля!",
        "settings-success-title": "Успешно!",
        "settings-fail-title": "Ошибка",
        "settings-account-change-success-caption": "Имя учетной записи успешно изменено",
        "settings-account-change-fail-caption": "Не удалось изменить имя учетной записи",
        "settings-language-change-success-caption": "Язык интерфейса успешно изменен",
        "settings-language-change-fail-caption": "Не удалось изменить язык интерфейса, проверьте подключение к интернету",
        "settings-theme-change-success-caption": "Тема интерфейса успешно изменена",
        "settings-theme-change-fail-caption": "Не удалось изменить тему интерфейса, проверьте подключение к интернету.",
        "settings-password-change-success-caption": "Пароль успешно изменен",
        "settings-password-change-fail-caption": "Не удалось изменить пароль."
      },
      "home-route": {
        "bottom-navbar-home-label": "Главная",
        "bottom-navbar-search-label": "Поиск",
        "bottom-navbar-profile-label": "Профиль",
        "home-greeting-subtitle": "Добро пожаловать в iCafePlay",
        "home-greeting-title": "Куда мы сегодня идем?",
        "home-search-button-label": "Поиск",
        "home-top-centers-title": "Лучшие центры",
        "home-top-centers-subtitle": "Откройте для себя наши лучшие центры",
        "home-center-of-the-day-title": "Центр дня",
        "home-center-of-the-day-subtitle": "Этот центр сегодня в центре внимания",
        "home-exception-hint": "Не удалось загрузить список центров",
        "search-input-hint": "Поиск",
        "profile-settings-bookings-label": "История бронирований",
        "profile-settings-bank-cards-label": "Мои банковские карты",
        "profile-settings-transactions-label": "История транзакций",
        "profile-settings-accounts-label": "Аккаунты",
        "profile-settings-settings-label": "Настройки",
        "profile-settings-support-label": "Поддержка",
        "profile-settings-logout-label": "Выйти",
        "profile-modals-bookings-empty-title": "Бронирования не найдены",
        "profile-modals-bookings-empty-hint": "У вас нет активных бронирований. Начните бронировать ПК, и они появятся здесь",
        "profile-modals-bookings-title": "Мои бронирования",
        "profile-modals-bookings-booking-date": "Дата",
        "profile-modals-bookings-booking-time": "Время",
        "profile-modals-bookings-booking-pc": "ПК",
        "profile-modals-bookings-booking-minutes": "Минуты",
        "profile-modals-bank-cards-empty-title": "Банковские карты не найдены.",
        "profile-modals-bank-cards-empty-hint": "У вас нет банковских карт. Вы можете привязать свою банковскую карту на странице любого центра",
        "profile-modals-bank-cards-title": "Мои банковские карты",
        "profile-modals-bank-cards-warning-title": "Предупреждение!",
        "profile-modals-bank-cards-warning-details": "Удаление приведет к удалению всех данных, связанных с банковскими картами, включая историю транзакций!",
        "profile-modals-bank-cards-remove-button-label": "Удалить",
        "profile-modals-transactions-dialog-title": "Выберите банковскую карту",
        "profile-modals-transactions-empty-title": "Транзакции не найдены",
        "profile-modals-transactions-empty-hint": "У вас нет транзакций. История ваших пополнений будет видна здесь",
        "profile-modals-transactions-title": "История транзакций",
        "profile-modals-transactions-transaction-center": "Центр:",
        "profile-modals-transactions-transaction-amount": "Сумма:",
        "profile-modals-transactions-transaction-date": "Дата:",
        "profile-modals-transactions-transaction-account": "Аккаунт:",
        "profile-modals-transactions-transaction-status": "Статус:",
        "profile-modals-transactions-exception-hint": "Не удалось загрузить список транзакций:",
        "profile-modals-accounts-empty-title": "Не найдено ни одного аккаунта",
        "profile-modals-accounts-empty-hint": "У вас нет ни одного аккаунта. Начните связывать аккаунты, и они появятся здесь",
        "profile-modals-accounts-title": "Мои аккаунты",
        "profile-modals-support-exception-hint": "Не удалось открыть Telegram",
        "profile-modals-support-exception-comment": "Не удалось обработать ссылку Telegram (",
        "profile-modals-logout-confirm-title": "Вы уверены?",
        "profile-modals-logout-confirm-hint": "Вы действительно хотите выйти из системы??",
        "profile-modals-logout-confirm-button-label": "Выйти",
        "profile-exception-hint": "Что-то пошло не так (",
      },
      "settings-route": {
        "change-name-section-title": "Настройки",
        "change-name-section-label": "Изменить имя аккаунта",
        "change-name-section-input-hint": "Имя",
        "change-name-section-button-label": "Сохранить",
        "language-section-title": "Персонализация",
        "language-section-label": "Изменить язык интерфейса",
        "dark-theme-section-label": "Изменить тему интерфейса",
        "theme-option-dark-label": "Темный",
        "theme-option-bright-label": "Светлый",
        "password-reset-section-title": "Сбросить пароль",
        "password-reset-section-old-label": "Старый пароль",
        "password-reset-section-old-input-hint": "Старый пароль",
        "password-reset-section-new-label": "Новый пароль",
        "password-reset-section-new-input-hint": "Новый пароль",
        "password-reset-section-button-label": "Сохранить"
      },
      "center-route": {
        "link-account-button-label": "Связать аккаунт",
        "link-account-button-label-alt": "Аккаунт",
        "center-account-title": "Аккаунт",
        "center-account-subtitle": "Баланс",
        "center-account-cash-balance-label": "Баланс аккаунта",
        "center-account-points-balance-label": "Баланс баллов",
        "center-account-coins-balance-label": "Баланс монет",
        "center-account-bonus-balance-label": "Бонусный баланс",
        "center-details-title": "Детали",
        "center-details-offers-label": "Предложения",
        "center-details-zones-label": "Зоны",
        "center-details-address-label": "Адрес",
        "center-call-failed-title": "Ошибка",
        "center-call-failed-subtitle": "Не удалось открыть номер телефона",
        "center-call-button-label": "Позвонить",
        "center-location-title": "Недоступно",
        "center-location-subtitle": "Локация центра недоступна",
        "center-location-button-label": "Локация",
        "center-subcenters-title": "Филиалы",
        "center-footer-button-topup-button-label": "Пополнить",
        "center-footer-button-booking-button-label": "Бронирование",
        "failed-to-load-data": "Не удалось загрузить центр (и связанные с ним) данные"
      },
      "bank-cards-route": {
        "bank-cards-route-title": "Новая банковская карта",
        "bank-cards-route-subtitle": "Выберите платежную систему",
        "bank-cards-card-details-label": "Данные карты",
        "bank-cards-card-details-input-hint": "Номер карты",
        "bank-cards-card-expiry-input-hint": "мм/гг",
        "bank-cards-name-on-card-input-hint": "Имя на карте",
        "bank-cards-phone-input-hint": "Номер телефона",
        "bank-cards-first-step-button-label": "Создать",
        "verification-code-sent-text": "Код подтверждения отправлен",
        "verification-code-timeout-label": "Код",
        "verification-code-input-label": "Введите одноразовый код, который вы получили",
        "bank-cards-second-step-button-label": "Подтвердить",
        "verification-code-resend-button-label": "Отправить код повторно",
        "verification-code-resent-text": "Новый код подтверждения отправлен",
        "link-bank-card-title": "Банковская карта не привязана",
        "link-bank-card-subtitle": "Ваша банковская карта не привязана к этому центру. Привяжите свою карту для выполнения онлайн-пополнений",
        "link-bank-card-button-label": "Привязать карту",
        "link-bank-card-failed-to-fetch": "Не удалось загрузить данные пользователя.",
      },
      "booking-route": {
        "booking-route-title": "Забронировать ПК",
        "member-input-hint": "Аккаунт",
        "center-input-hint": "Центр",
        "date-input-hint": "Дата",
        "time-input-hint": "Время",
        "minutes-input-hint": "Минуты",
        "booking-primary-button-label": "Забронировать",
        "booking-failed-to-fetch-list": "Не удалось загрузить компьютеры и список бронирований"
      },
      "authorization-route": {
        "email-input-hint": "Почта",
        "password-input-hint": "Пароль",
        "forgot-password-button-label": "Забыли пароль?",
        "login-button-label": "Войти",
        "register-button-label": "Регистрация",
      },
      "registration-route": {
        "registration-route-title": "Регистрация",
        "name-input-hint": "Имя",
        "country-input-hint": "Выберите страну",
        "choose-country-search-hint": "Поиск",
        "email-input-hint": "Email",
        "password-input-hint": "Пароль",
        "empty-input-title": "Пожалуйста, заполните все обязательные поля!",
        "login-button-label": "Зарегистрироваться",
        "failed-to-fetch": "Не удалось загрузить список стран.",
      }
    }
  };

  static String translate(language, route, text) {
    return CivicLocale.dictionary[language][route][text];
  }
}